### ISSUE TITLE
Search values need to support Upper Limit and Lower Limit

### ISSUE THREAD

**Issue by DrKentB** [gwosc-tutorial/gwosc-catalog#16]
Each of the search values: pastro, far, snr needs to support the upper_limit and lower_limit fields. 

I think these should also support min, mean, max just like the parameters even though that has seldom been used.

**Comment by martinberoiz** [comment]
Ouch, this will introduce some clashing names, unless we nest each parameter with its own upper, lower, etc. I'm not against nesting as you may have noticed.

**Comment by jkanner** [comment]
I think nesting is fine for these parameters.  On our side, parameters use the same model whether they are for PE or search, so it makes sense to treat the search and PE parameters the same.  We should have good defaults, so that if a user does not define "upper_limit" or "lower_limit", they simply default to `False`.

**Comment by martinberoiz** [comment]
Completed
